version: '3.8'

services:
  webserver:
    build: .
    ports:
      - 8090:80
      - 2222:22
    networks:
      - connwebserver
    volumes:
      - dev:/var/www/
  serverdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1035Botero
    ports:
      - 5432:5432
    networks:
      - connwebserver
      - connserverdb
    volumes:
      - pgdata:/pgdata/
      
  servercache:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - connserverdb
    volumes:
      - redisdata:/redis/data
  clientedb:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=jacal2211@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1035Botero
    ports:
      - 8080:80
    networks:
      - connserverdb

volumes:
  pgdata:
  dev:
  redisdata:
  
networks:
  connwebserver:
    driver: bridge
  connserverdb:
    driver: bridge

  